import { Injectable } from '@angular/core';
import * as DemoOneWorker from 'worker-loader!../../web-workers/worker-demo1/demo1.worker.bundle.js';
import * as DemoTwoWorker from 'worker-loader!../../web-workers/worker-demo2/demo2.worker.bundle.js';


@Injectable()
export class WebWorkerService {

  demoOneWorker: Worker = new DemoOneWorker();
  demoTwoWorker: Worker = new DemoTwoWorker();

  constructor() {
  }

  initialize() {

    // Demo 1 worker
    this.demoOneWorker.onmessage = function ( event ) {
      const data = event.data; // "This text was generated by template B"
      console.log('Web Worker ONE Response: ', data);
    };

    const that = this;

    setTimeout(function () {
      console.log('\n\nPosting message to web worker ONE');
      that.demoOneWorker.postMessage('Worker ONE Data');
    }, 1000);

    // Demo 2 worker
    this.demoTwoWorker.onmessage = function ( event ) {
      const data = event.data; // "This text was generated by template B"
      console.log('Web Worker TWO Response: ', data);
    };

    setTimeout(function () {
      console.log('\n\nPosting message to web worker TWO');
      that.demoTwoWorker.postMessage('Worker TWO Data');
    }, 2000);
  }

}
